### ISSUE TITLE
Make server master failover can be tested

### ISSUE THREAD

**Issue by amyangfei** [hanfei1991/microcosm#42]
After https://github.com/hanfei1991/microcosm/pull/41 we have supported to deploy multiple server maters for HA, we still need some features to make executor can work when server master suffers leader transfer, including 
- [x] Support gRPC redirect to leader in server master #56
- [x] Support server master to load metadata to rebuild executors information when it changes to leader OR the executor maintains a list of server master and updates leader periodically	#47 
- [x] Support server master to rebuild job master information.

**Comment by nongfushanquan** [comment]
Load metadata to restore the job manager

**Comment by amyangfei** [comment]
One failover scenario:
- Server master, one job with a job master and several tasks are running.
- Server master crashes and restarts, it reloads enough information.
- Then cancel job.

Questions:
1. Should server master cancel job master, and job master cancels other tasks. Or server master cancels all tasks belonging to this job?
2. If server master cancels all tasks, it should persist metadata of each task.
3. Who is responsible for task rescheduling, job master? If so, should server master know rescheduling?

**Comment by hanfei1991** [comment]
1. Server master manages job masters, so it's ok to cancel job master. However the rest tasks should be stopped by job master. You can refer to the current implemention just as what I write.
2. I think server master can see all tasks in the meta store and job master is a special kind of task. Server master should load and reschedule all the job masters, and each job master manages its own tasks.
3. Reschedule happens when executor/tasks crash, and job master should be in charge of rescheduling. However, resource manager should answer job master the schedule result.

**Comment by amyangfei** [comment]
more tasks ref: #190
